### ISSUE TITLE
Issues when discord is not running

### ISSUE THREAD

**Issue by Taelyn** [MarshMello0/Editor-Rich-Presence#6]
Gives tons of log errors when discord isnt running and a popup with a error when going in PlayMode.

Please add a check for when discord isnt running :)

**Comment by MarshMello0** [comment]
Thanks for the report, I've committed a fix for it. 
You can instantly get it by [pulling it from the git repo](https://docs.unity3d.com/Manual/upm-ui-giturl.html) but I will send it to unity for review.

**Comment by MarshMello0** [comment]
It has been approved, 3.1.1 should solve this issue.

**Comment by Taelyn** [comment]
Thanks!
