### ISSUE TITLE
Discord Canary not connecting with Rich Presence

### ISSUE THREAD

**Issue by Metokel** [MarshMello0/Editor-Rich-Presence#7]
The rich presence does not activate when I am using Discord Canary

**Comment by MarshMello0** [comment]
Thanks for the report. It was a simple fix with checking the correct process name.

I've sent this off to Unity to update the package on the asset store.
They say it will take about two business days. You can instantly get it by [pulling it from the git repo](https://docs.unity3d.com/Manual/upm-ui-giturl.html)

**Comment by Metokel** [comment]
Thanks for the quick fix.

**Comment by MarshMello0** [comment]
[The update is live! ](https://assetstore.unity.com/packages/tools/utilities/editor-rich-presence-178736#releases)
