### ISSUE TITLE
ResultException: NotRunning

### ISSUE THREAD

**Issue by ReaperCalli** [MarshMello0/Editor-Rich-Presence#8]
![image](https://user-images.githubusercontent.com/59681368/141288211-8c430e20-9d79-41d7-a299-9d327baa389c.png)
Having this problem with my Unity Project. I'm using 2020.3.20f1

**Comment by ReaperCalli** [comment]
It only happens on discord canary. I tried stable and is working fine

**Comment by MarshMello0** [comment]
In the details tab of the task manager. What is the discord canary exe name?

**Comment by ReaperCalli** [comment]
Its DiscordCanary.exe, though I think it was fixed last update.

**Comment by ReaperCalli** [comment]
I'm gonna close the issue since it was an issue with using powercord (a discord mod) which must have caused that issue I removed it and it worked again. So I'm sorry for somehow wasting your time and thanks you for responding.
